### ISSUE TITLE
filetags on windows

### ISSUE THREAD

**Issue by ottopichlhoefer** [novoid/filetags#2] opened 2016-04-30 09:01 UTC
I have been using filetags  `PROG_VERSION_NUMBER = u"0.3" PROG_VERSION_DATE = u"2015-01-02"` successfully for some time now. 

I am using `Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32`

Now I tried to ipgrade to filetags `PROG_VERSION_NUMBER = u"0.6beta" PROG_VERSION_DATE = u"2016-01-08"` but ran into an error.

```
Traceback (most recent call last):
  File "filetags.py", line 973, in <module>
    main()
  File "filetags.py", line 887, in main
    vocabulary = sorted(locate_and_parse_controlled_vocabulary(args[0]))
TypeError: 'bool' object is not iterable
```

Unfortunately I do not know Python at all to be able to tackle this issue.

Thanks for the great script.

**Comment by novoid** [comment] 2016-05-02 12:03
Hi!

I need more information on this issue:

- what environment are you using (cmd.exe, Cygwin, Babun, MingW32, ...)?
- what is the complete command line including the file(s) you want to tag and the folder used?
- are you using a controlled vocabulary (i.e., a file named ".filetags")? If yes, in what folder?

Thanks!

**Comment by ottopichlhoefer** [comment] 2016-05-02 12:13
- The environment is `cmd.exe`
- The command line looks like this: `python C:\Dropbox\NRK_Project\Software\scripts\filetags.py -i W:\Dropbox\Buchhaltung\Belege\2016-04-25-01-30-17_.pdf`
- Yes, I am using `.filetags`in the same directory as the file itself `W:\Dropbox\Buchhaltung\Belege\`

Thanks

**Comment by novoid** [comment] 2016-05-02 12:21
Unfortunately, the Windows I have access to doesn't have a working Python environment.

Can you assist me in debugging the issue?

Please do edit "filetags.py" and add before line 887:
```print '[' + str(args[0]) + ']'```
Please do make sure that the number of leading spaces matches the number of leading spaces of the line afterwards.

**Comment by ottopichlhoefer** [comment] 2016-05-02 12:23
Maybe the format of the `.filetags` is the problem. It looks something like this:

```
# ;;; -*- mode: org; -*-
# [[file+sys:Kontenrahmen-AUT.xlsx]]
0000 Konto xyz
0001 Konto xyz
0003 Konto xyz
442xyz Volksbank
942xyz Bank Austria
374xyz American Express

* Klasse 1 Aktiva: Vorraete
# 1000 Bezugsverrechnung
# 1100 Rohstoffe
# 1200 Bezogene Teile
# 1300 Hilfsstoffe
# 1350 Betriebsstoffe
# 1360 Vorrat Energietraeger
# 1400 Unfertige Erzeugnisse
# 1500 Fertige Erzeugnisse
1600 Handelswarenvorrat
# 1700 Noch nicht abrechenbare Leistungen
# 1900 Wertberichtigungen
# 1800 Geleistete Anzahlungen
```

As you can see, it contains a complete "Kontenrahmen" and I outcomment unnecessary entries in org-mode. 

I will try debugging the python script later today.

Thanks a lot!

**Comment by novoid** [comment] 2016-05-02 12:29
I see.

OK, I am not completely sure if this is also the cause for the Traceback you mentioned above.

However, the `.filetags` file format is one tag per line with no comments. So please do use a valid `.filetags` file and test again. I'll close the issue for now. We'll reopen it, if you got the error with a valid `.filetags` file as well.

**Closed by novoid** 2016-05-02 12:29 UTC

**Comment by ottopichlhoefer** [comment] 2016-05-02 16:27
Danke, funktioniert so.

**Comment by ottopichlhoefer** [comment] 2016-05-05 15:23
Hello,

I gave it another try and cannot get the recent version of filetags to work on windows. I tested without a tags file, this time:

First the version `0.3 `works fine:
```
python filetags_.py -i test.pdf

Please enter tags, separated by "-"; abort with Ctrl-C; complete 4 tags with TAB

        ,---------.
        |  ?     o |
        `---------'

Tags: tag
INFO     adding tags "tag" ...
```

Then version `0.6beta`:

```
python filetags.py -i test.pdf

Please enter tags, separated by " "; abort with Ctrl-C; complete 4 tags with TAB

        ,---------.
        |  ?     o |
        `---------'

Tags: tag
INFO     adding tags "tag" ...
Traceback (most recent call last):
  File "filetags.py", line 973, in <module>
    main()
  File "filetags.py", line 966, in main
    handle_file(filename, tags_from_userinput, options.remove, options.dryrun)
  File "filetags.py", line 383, in handle_file
    print u"   %s   ÔåÆ   %s" % (filename, new_filename)
  File "c:\portablejekyll\python\app\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2192' in position 14: character maps to <undefined>
```

BTW (U+2192) is Unicode Character 'RIGHTWARDS ARROW' 

Thanks

**Comment by novoid** [comment] 2016-05-05 19:12
Hi Otto!

Well, it seems to be the case that your system can't display Unicode characters I used in my tool.
I could replace the three Unicode characters in lines 379, 383, and 385. But that would be cowardly ;-)

However, I do think I tested filetags with those Unicode characters in the output on my Windows system at work. Can't verify this until next week though.

In the meantime, please do check out my latest version where I added a try-catch-clause for UnicodeEncodeError of terminals that can't handle Unicode.

**Comment by ottopichlhoefer** [comment] 2016-05-06 07:04
The latest version unfortunately also throws an error:

```
> python C:\Dropbox\NRK_Project\Software\scripts\filetags3.py -i test.pdf
Traceback (most recent call last):
  File "C:\Dropbox\NRK_Project\Software\scripts\filetags3.py", line 982, in <module>
    main()
  File "C:\Dropbox\NRK_Project\Software\scripts\filetags3.py", line 896, in main
    vocabulary = sorted(locate_and_parse_controlled_vocabulary(args[0]))
TypeError: 'bool' object is not iterable
```

The codepage of my terminal is 850. Changing it to 437, which contains U2192, didn’t do the trick either.

In an y case, thanks a lot. I’ll use the old version of the script in the meantime.

**Comment by ottopichlhoefer** [comment] 2016-05-06 07:17
This might be related:
http://stackoverflow.com/questions/30923819/why-python-2-7-on-windows-need-a-space-before-unicode-character-when-print

**Comment by novoid** [comment] 2016-05-06 08:25
The stackoverflow-issue you mentioned is not related to this issue.

It was my fault. Please do test again the latest version. Sorry for your inconvenience and thanks for reporting your issues with Windows!

**Comment by ottopichlhoefer** [comment] 2016-05-06 08:51
Thanks,

Works now with one tag. If there is more than one tag, there still is an
error. This seems to be related to the ’dot operator’ on line 759.

python filetags.py -i "test -- test eins zwei.pdf"

Please enter tags, separated by " "; abort with Ctrl-C

        ,---------.
        |  ?     o |
        `---------'


  Previously used tags in this directory:
Traceback (most recent call last):
  File "filetags.py", line 982, in <module>
    main()
  File "filetags.py", line 930, in main
    print_tag_shortcut_with_numbers(upto9_tags_from_filenames_of_same_dir_list,
tags_get_added=True)
  File "filetags.py", line 759, in print_tag_shortcut_with_numbers
    print u'    ' + u' Ôïà '.join(list_of_tag_hints)
  File "c:\portablejekyll\python\app\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u22c5'
in position 13: character maps to <undefined>

ᐧ

2016-05-06 10:25 GMT+02:00 novoid <notifications@github.com>:

**Comment by novoid** [comment] 2016-05-06 09:00
Damn. I did not get all the Unicode characters I am using for my fancy console output.

However, you did. Added another exception for it.

This is getting embarrassing for me ;-)

**Comment by ottopichlhoefer** [comment] 2016-05-06 09:38
Maybe one more colon to make the soup perfect :-)

python filetags.py -i "test -- test eins zwei.pdf"
  File "filetags.py", line 759
    try
      ^
SyntaxError: invalid syntax

I added the colon and the script works fine.

I really appreciate your help,
Otto


​P.S.: Feature request

It would be nice to change the number of tags in the directory through a
command line switch and possibly display the tags in list form. My use case
is that I have at current 40 tags for files that I exchange with my tax
accountant.

​


ᐧ

2016-05-06 11:00 GMT+02:00 novoid <notifications@github.com>:

**Comment by novoid** [comment] 2016-05-06 10:05
OMG, definitely embarrassing :-)

Feature request: what do you mean by "change the number of tags in the directory"?

**Comment by ottopichlhoefer** [comment] 2016-05-06 12:15
Sorry to be unclear.

When filetags.py -i is invoked it collects previously used tags in the
directory and displays max. 9 of them to be selected by a number.

It would be good to optionally increase the number of displayed tags and
also display them in a tabular form for selection. This would be helpful at
least in my use case.
ᐧ

2016-05-06 12:05 GMT+02:00 novoid <notifications@github.com>:

**Comment by novoid** [comment] 2016-05-06 15:46
Oh I see.

Well, then I'd have to re-think the complete shortcut entry process. So far, the user is able to enter "426" and the 4th, second, and 6th tag is used. With >10 tags, the shortcut entry has to be done completely different.

I'd say you stick to the TAB completion instead: press TAB twice and you see all available completion tags.
