### ISSUE TITLE
Tagtree Attribute Error: Property '<unknown>.Targetpath' can not be set in Windows 11

### ISSUE THREAD

**Issue by chaicurioquest** [novoid/filetags#70] opened 2024-06-30 18:45 UTC
@novoid Hi,
I am getting the following error "`AttributeError: Property '<unknown>.Targetpath' can not be set`" while running the filetag with tagtree in recursive mode. 

>>`filetags --verbose --tagtrees --recursive --tagtrees-handle-no-tag no-tags --tagtrees-dir=E:\archive\.filetags_tagtree`

The screenshot is below,

![Screenshot 2024-07-01 000958](https://github.com/novoid/filetags/assets/173520446/c72bf70e-5129-46e3-9eb4-128ef91a5a5c)

Thanks.

**Comment by chaicurioquest** [comment] 2024-09-10 04:12
@novoid Hi, 
Even when I run D:\Python\Python312\Scripts\filetags.exe" --tagtrees --tagtrees-depth 3,
I am getting following error, 
![image](https://github.com/user-attachments/assets/7ffc7e8c-df3d-487e-b485-f2833ed5b856)
Any help? Thanks.

**Comment by chaicurioquest** [comment] 2024-09-10 04:35
I have narrowed the issue, when the file name has special character(s) as below, it's throwing error,
2024-05-19 [Nato Science Series II_ **№88**] André Anders (auth.), Efim Oks, Ian Brown (eds.) - Emerging Applications of Vacuum-Arc-Produced Plasma, Ion and Electron Beams (2002, Springer) [10.1007_978-94-010-0277-6]
NTU GIEE**｜**Graduate Institute of Electronics Engineering.pdf. Is there any way to handle error exception when special character in file name?

**Comment by novoid** [comment] 2024-09-15 14:59
Well, I created your file names on my Linux system and can not reproduce the issue. Unfortunately, I don't have access to Windows.

**Comment by novoid** [comment] 2024-09-15 15:01
Here is my output in case somebody with access to Windows would like to volunteer:

```
vk@sting ~2d/2024-09-15 filetags issue 70/files % filetags --tagtrees --verbose --tagtrees-dir=../tagtrees                                                                                                                    [15/1907]
DEBUG    2024-09-15 16:57:32,974 extracting list of files ...
DEBUG    2024-09-15 16:57:32,974 len(options.files) [0]
DEBUG    2024-09-15 16:57:32,974 0 filenames found: []
DEBUG    2024-09-15 16:57:32,974 reported console width: 231 and height: 58   (80/80 is the fall-back)
DEBUG    2024-09-15 16:57:32,974 locate_and_parse_controlled_vocabulary: called with startfile: "False"
DEBUG    2024-09-15 16:57:32,974 locate_and_parse_controlled_vocabulary: called in cwd: /home/vk/tmp/2del/2024-09-15 filetags issue 70/files
DEBUG    2024-09-15 16:57:32,974 locate_file_in_cwd_and_parent_directories: called with startfile "/home/vk/tmp/2del/2024-09-15 filetags issue 70/files" and filename ".filetags" ..                                          
DEBUG    2024-09-15 16:57:32,974 locate_file_in_cwd_and_parent_directories: startfile [/home/vk/tmp/2del/2024-09-15 filetags issue 70/files] is a directory, using it as starting_dir [/home/vk/tmp/2del/2024-09-15 filetags issue 70/f
iles] .....                                            
DEBUG    2024-09-15 16:57:32,974 locate_file_in_cwd_and_parent_directories: looking for ".filetags" in directory "/home/vk/tmp/2del/2024-09-15 filetags issue 70" .......
DEBUG    2024-09-15 16:57:32,974 locate_file_in_cwd_and_parent_directories: found ".filetags" in directory "/home/vk" ........
DEBUG    2024-09-15 16:57:32,974 locate_and_parse_controlled_vocabulary: locate_file_in_cwd_and_parent_directories returned: /home/vk/.filetags
DEBUG    2024-09-15 16:57:32,974 locate_and_parse_controlled_vocabulary: .filetags found: /home/vk/.filetags
DEBUG    2024-09-15 16:57:32,974 locate_and_parse_controlled_vocabulary: found controlled vocabulary

[...]

DEBUG    2024-09-15 16:57:32,974 handling option for tagtrees
DEBUG    2024-09-15 16:57:32,974 User overrides the default tagtrees directory to: ../tagtrees
DEBUG    2024-09-15 16:57:32,974 found old tagfilter directory "../tagtrees"; deleting directory ...
DEBUG    2024-09-15 16:57:32,975 re-creating tagfilter directory "../tagtrees" ...
DEBUG    2024-09-15 16:57:32,975 get_files_of_directory(/home/vk/tmp/2del/2024-09-15 filetags issue 70/files) called and traversing file system ...
DEBUG    2024-09-15 16:57:32,975 get_files_of_directory(/home/vk/tmp/2del/2024-09-15 filetags issue 70/files) finished with 2 items
DEBUG    2024-09-15 16:57:32,975 locate_file_in_cwd_and_parent_directories: called with startfile "/home/vk/tmp/2del/2024-09-15 filetags issue 70/files" and filename ".filetags" ..
DEBUG    2024-09-15 16:57:32,975 locate_file_in_cwd_and_parent_directories: startfile [/home/vk/tmp/2del/2024-09-15 filetags issue 70/files] is a directory, using it as starting_dir [/home/vk/tmp/2del/2024-09-15 filetags issue 70/f
iles] .....
DEBUG    2024-09-15 16:57:32,975 locate_file_in_cwd_and_parent_directories: looking for ".filetags" in directory "/home/vk/tmp/2del/2024-09-15 filetags issue 70" .......
DEBUG    2024-09-15 16:57:32,975 locate_file_in_cwd_and_parent_directories: found ".filetags" in directory "/home/vk" ........
DEBUG    2024-09-15 16:57:32,975 generate_tagtrees: I found controlled_vocabulary_filename "/home/vk/.filetags" which I'm going to link to the tagtrees folder
DEBUG    2024-09-15 16:57:32,975 create_link(/home/vk/.filetags, ../tagtrees/.filetags) called
INFO     2024-09-15 16:57:32,975 Creating tagtrees and their links. It may take a while …  (exponentially with respect to number of tags)
DEBUG    2024-09-15 16:57:32,975 get_tags_from_files_and_subfolders called with startdir [/home/vk/tmp/2del/2024-09-15 filetags issue 70/files], cached startdirs [0]
DEBUG    2024-09-15 16:57:32,975 get_tags_from_files_and_subfolders: Writing 1 tags in cache for directory: /home/vk/tmp/2del/2024-09-15 filetags issue 70/files
DEBUG    2024-09-15 16:57:32,975 generate_tagtrees: handling file "/home/vk/tmp/2del/2024-09-15 filetags issue 70/files/Nato Science Series II_ №88] André Anders (auth.), Efim Oks, Ian Brown (eds.) - Emerging Applications of Vacuum
-Arc-Produced Plasma, Ion and Electron Beams (2002, Springer) -- foo.pdf" …
DEBUG    2024-09-15 16:57:32,975 create_link(/home/vk/tmp/2del/2024-09-15 filetags issue 70/files/Nato Science Series II_ №88] André Anders (auth.), Efim Oks, Ian Brown (eds.) - Emerging Applications of Vacuum-Arc-Produced Plasma, 
Ion and Electron Beams (2002, Springer) -- foo.pdf, ../tagtrees/foo/Nato Science Series II_ №88] André Anders (auth.), Efim Oks, Ian Brown (eds.) - Emerging Applications of Vacuum-Arc-Produced Plasma, Ion and Electron Beams (2002, 
Springer) -- foo.pdf) called
DEBUG    2024-09-15 16:57:32,975 generate_tagtrees: handling file "/home/vk/tmp/2del/2024-09-15 filetags issue 70/files/NTU GIEE｜Graduate Institute of Electronics Engineering -- foo.pdf" …
DEBUG    2024-09-15 16:57:32,975 create_link(/home/vk/tmp/2del/2024-09-15 filetags issue 70/files/NTU GIEE｜Graduate Institute of Electronics Engineering -- foo.pdf, ../tagtrees/foo/NTU GIEE｜Graduate Institute of Electronics Engin
eering -- foo.pdf) called
INFO     2024-09-15 16:57:32,975 Number of links created in "../tagtrees" for the 2 files: 2  (tagtrees depth is 2) 
DEBUG    2024-09-15 16:57:32,975 platform.system() is: [Linux]
DEBUG    2024-09-15 16:57:33,493 successfully finished.
vk@sting ~2d/2024-09-15 filetags issue 70/files %
```

**Comment by nbehrnd** [comment] 2024-09-16 13:38
@chaicurioquest I presume the greater picture of tagging the pdf files here is to organize (academic) papers.  If this were the case, I suggest to invest some time into [reference managers](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software); typically, larger research/university libraries host workshops to present their pros and cons, and how to use them efficiently.  There is plenty material for self study, too.

One example of them is [zotero](https://www.zotero.org/) which is open source, freely available, cross-platform.  It allows to manage the fetch (and completion) of the pdf and their bibliographic data where possible, to mark and annotate the documents, to organize the material in hierarchies and eventually help you to write a new report/paper with a word processor like Word, Writer or a text processor like a [LaTeX engine](https://en.wikipedia.org/wiki/LaTeX), [Markdown](https://en.wikipedia.org/wiki/Markdown) or [pandoc](https://pandoc.org/) based workflow.  This can be very useful in many ways -- regardless if the collection(s) of pdf are your library, or partially shared collection within a group.  An example recently seen how zotero integrates the concept of tags is [Mastering Zotero: Working with Tags](https://h5pstudio.ecampusontario.ca/content/6563) by Kris Joseph, York University, Canada as part of a [series](https://pressbooks.library.yorku.ca/masteringzotero/front-matter/introduction/) of installments.

I speculate the suggestive bold about `№88` is about single character `№` itself.  This isn't part of original ASCII (7-bit), but one of later character code page [Windows-1251](https://en.wikipedia.org/wiki/Windows-1251) extension to support some Cyrillic characters [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) (about Latin Script) does not.  Any objections to process ``№88` information  as volume 88 of a journal, or book series which then is then easier understood and processed by a reference manager regardless which character code page is used (it should be a lesser issue with UTF-8 character encoding).

**Comment by novoid** [comment] 2024-09-16 13:56
> I presume the greater picture of tagging the pdf files here is to organize (academic) papers.

No.

filetags is a tool that offers simple file tagging. It is method-agnostic and doesn't imply any particular method. You can think of many multi-classification workflows that may be implemented also by filetags. Only if you need concepts not implemented in filetags such as tag inheritance, categorizing vs. describing tags, ... you do face limitations of filetags.

Back to the issue at hand: my guess would be that Windows does introduce issues by following non-UTF-8 charsets where GNU/Linux systems do not have an issue with. However, for further analysis, I'd need access to a Windows license and at least a VM or such. My limited time budget doesn't allow for a setup process associated with that (my guess would be at least an hour for a VM) with unclear result.

You can - however - try to drill down the problem by removing special characters from your file name and write down here after which step the issue was gone. E.g., removing the №88 would be one of the first things I'd try.

HTH

**Comment by chaicurioquest** [comment] 2024-09-16 16:48
@nbehrnd Thank you for the valuable suggestion. I rarely used Zotero before for article reference management. My file & folder structure was quite normal like other Windows user (for e.g. different hard drive for different categories of work flow such as C drive for Windows files, D drive work and E drive backup. 

Big thanks to @novoid for contemplating his ideas into effective PIM. Before adopting into file taging I did some research on different file management  approaches like The [PARA Method](https://fortelabs.com/blog/para/), [Johnny.Decimal ](https://johnnydecimal.com/) and few other techniques. I was badly in need of managing my digital data since it was kind of mess piled up mess for more than decade. Even I have bought Google Drive space for sync up my data. I found filetaging is intuitive, straight forward, built naturally over the years. 
Once I have got an idea of filetaging, I tried ISO formatted file name (yyyy-mm-dd), tag filter and so on from [various blogs](https://karl-voit.at/managing-digital-photographs/) from @novoid. Recently, I had a requirement of managing notes. I stumbled upon emacs-org features, and I am figuring out to adopt the workflow for note-taking, linked notes(Org-Roam) and visualization(Org-Roam-Graph) and Advanced Citation Management(Org-Ref) similar to [Obsidian](https://obsidian.md/). Still, I have more things to streamline this task. 
Coming to Zotero again, I recently tried Zotero for articles references with tags (thanks again Karl Voit for introducing tags) as shown in Fig 1. 
![image](https://github.com/user-attachments/assets/59d7824e-4bf5-4737-a90a-a1b806642c54) Fig 1. 

I am trying to integrate Karl Voit PIM method (for e.g. maintaing ISO file naming Fig 2 & 3)  system with other workflows (1. Zotero for article references 2. Emacs org linking with Zotero references including annotation, notes, tags through Better BibTeX (For exporting library collections and bibliographies) for Zotero plugin, Zotfile (For extracting annotations and notes) and org-zotxt (For linking and inserting Zotero citations in Org mode) 3. Emacs org for task management, calendar and so on) 
![image](https://github.com/user-attachments/assets/cd8fc8f4-1b81-4610-b5a1-e3a16f92ae6a)
Fig 2.  
![image](https://github.com/user-attachments/assets/9f86bbc3-5478-45f7-ba3c-2b4b083fbd18)
Fig 3. 
I am a beginner at managing digital files and workflows in this approach. Excuse if any points are not accurate/understandable.

`This new file name is simple enough to not cause a problem for tagging by filetags engaged independently to the mechanism by zotero. And -- if wanted -- to later reconnect the pdf in question to the particular record in the zotero database.`. 
I will try to tag in article name (though Zotero GUI retrieve the articles based on tags) while renaming the file to maintain consistency with file-tagging. 

Back to the issue: I removed the special characters and it worked. 

Thank you, @novoid and @nbehrnd.

**Comment by novoid** [comment] 2024-09-16 17:14
Glad that you could make it run.

Sorry, that special characters may introduce such a nasty issue in 2024. :pensive: 

I honestly don't get the Zotero discussion here. (That's not intended as criticism.)

A common pattern in my workflows is that I either (A) manage meta-data of files in my Org-mode or (B) in the file system with optional meta-data within Org-mode. I rarely manage meta-data in both spots.

For (A), I mostly try to get any unique file name, not renaming the whole thing to my liking as long as I get an idea what it contains. Using path-independent links https://karl-voit.at/2022/02/10/lfile/ I link them at places in my Org-mode where I usually start the retrieval process for those type of files.

Examples for (B) are my own photographs, cliparts, fun files, ...

HTH

I close this issue for now. I may return to it when I have a working Windows environment in the future to analyse the issue any further.

**Closed by novoid** 2024-09-16 17:14 UTC
Labels: bug, help wanted, quickfix
