### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by sparky-vision** [novoid/filetags#66] opened 2024-01-16 21:16 UTC
Installation via pip. Calling filetags with any file, anywhere, results in the following output:

`Traceback (most recent call last):`
`  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,`
 ` File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\Scripts\filetags.exe\__main__.py", line 4, in <module>`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\filetags\__init__.py", line 51, in <module>
    save_import('readline')   # for raw_input() reading from stdin`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\filetags\__init__.py", line 35, in save_import
    globals()[library] = import_module(library)`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()`
 ` File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)`
 ` File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)`
`  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)`
  `File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):`
`  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)`
`AttributeError: module 'collections' has no attribute 'Callable'`

Output text formatted so it matches the screen output. Thoughts?

**Comment by novoid** [comment] 2024-01-24 18:35
This seems to be a duplicate of https://github.com/novoid/filetags/issues/54 or https://github.com/novoid/filetags/issues/51 or https://github.com/novoid/filetags/issues/49

In any case, that's related to the pyreadline library and a potential wrong dependency setup and not the code of filetags in particular.

**Closed by novoid** 2024-01-24 18:35 UTC
